### ISSUE TITLE
Windows UI has stopped responding - Value too large or too small...

### ISSUE THREAD

**Issue by mruno** [AirVPN/Eddie#101]
The following error has occurred twice in the past week:

![error](https://user-images.githubusercontent.com/6078925/67602073-759f0e00-f73b-11e9-9ff1-a1b35790ebfe.PNG)

After the crash, openvpn appears to be running, as reopening eddie gives error it (openvpn) is already open.

**Comment by AirVPN** [comment]
Resolved for everyone (with a server-side fix, don't need to update Eddie).
