### ISSUE TITLE
Network locking not working in linux if kernel modules compressed with zstd compression algorithm

### ISSUE THREAD

**Issue by Optimus22Prime** [AirVPN/Eddie#104]
Network locking not working in linux if kernel modules compressed with zstd compression algorithm, I got "Exception: Unable to initialize iptable_filter module" message. This module modprobe'd and rmmod'ed nicely from hands by the way. Changing modules compression algorithm back to xz fixing issue. It will be nice if Eddie will not depend from such thing as kernel modules compression type (presume module file extension is the key, xz or zstd) , because this may wary in different distros, and can be silently changed by kernel package maintainers, as it was in my case. 

Please, look at kmod man page, because kmod is conventional and universal way to do modules insertion\removing in all linux distros.

**Comment by AirVPN** [comment]
In the latest experimental 2.19.4, we removed the custom C++ module management and revert to a call to modprobe, to avoid (also in future) this kind of issue. Thanks.

**Comment by reiandrea** [comment]
test

**Comment by reiandrea** [comment]
test

**Comment by caseyjp11** [comment]
I don't know whether to open a new issue, or just reopen this one. I'm using 2.20.0 and this is still happening. The lock fails with kernel error messages. You click through that dialog and Eddie starts normally.
