### ISSUE TITLE
Incorrect display under Kubuntu

### ISSUE THREAD

**Issue by Ravenbird** [AirVPN/Eddie#105]
I am using Xubuntu 20.04, Ubuntu Mate 20.04 and Lubuntu 20.04 in parallel and since the latest Kubuntu 20.04. In all except Kubuntu Eddie is displayed correctly. They were all installed in the same way. I don't know if this is a general problem with Kubuntu/KDE/QT or if one or more packages have to be installed to make Eddie work as it should. In any case it looks like here on Kubuntu:

![AirVPN Eddie](https://user-images.githubusercontent.com/2757648/91445103-f6f09100-e875-11ea-9311-0303dca94c7e.png)

**Comment by Nisc3d** [comment]
I have the same Problem on Arch with KDE.

![grafik](https://user-images.githubusercontent.com/7361310/94041504-99932580-fdca-11ea-9b73-2b1817e2227b.png)

**Comment by AirVPN** [comment]
This bug was resolved in previous beta release, and now in the latest stable release. Thanks. Close.
