### ISSUE TITLE
Possible to use Eddie ( Proxy/Tor ) with TorBrowser ? [ Win] 

### ISSUE THREAD

**Issue by skyerjoe** [AirVPN/Eddie#106]
Some Apps like Electrum (Bitcoin Wallet) recognize the TorStack inside the TorBrowser. 

So u dont have to install the Core Tor Client just install and running the TorBrowser and the Apps is running over Tor. 

Is this also possible with Eddie ? 

best regards

**Comment by AirVPN** [comment]
We just re-tested download TorBrowser directly with Win, macOS and Ubuntu, after Eddie -> Preferences -> Proxy -> Tor , and works. Please reopen with a specific error or use-case.
