### ISSUE TITLE
Eddie 2.18.9 macOS client restores network interface DNS servers in the wrong order

### ISSUE THREAD

**Issue by futknuckle** [AirVPN/Eddie#111]
Eddie 2.18.9 running on a Mac Pro (2019) with macOS 10.15.7 (19H2) 

I have two DNS servers set in **System Preferences > Network > Advanced > DNS > DNS Servers**:

**10.0.0.5** - primary DNS server (my own local BIND daemon) is always the first in the list
**10.0.0.1** - secondary DNS server (my router) - second in the list

When I disconnect from VPN, Eddie restores my DNS servers in the opposite order:

**10.0.0.1** - since it is now listed **first**, my **router** becomes **primary**
**10.0.0.5** - my own local BIND daemon _should_ be primary, but is now **secondary**

For me this becomes a real problem because when Eddie swaps the order of the DNS servers, 10.0.0.1 becomes the primary server, and since 10.0.0.1 is my router, my internal hostnames won't be found.

**_Eddie should never change the order of user's DNS entries!_**

**Comment by AirVPN** [comment]
This bug was fixed in 2.19.x beta release, and now in the stable release. Thanks. Close.
