### ISSUE TITLE
Error when using generic OVPN - message box says contact support

### ISSUE THREAD

**Issue by TriggerDingus** [AirVPN/Eddie#115]
Greetings.
I'm looking forward to using Eddie with generic OVPN profiles that are created by my provider. I use these profiles regularly without Eddie, however, I'm receiving an error when trying to connect via Eddie.
What I've done:
Per instructions, I went to Advanced and selected Multi-Providers support
I went to providers tab, added an entry and within the new entry I selected the directory where my OVPN files are stored (3 of them) along with my username and password for the profiles
When saving, I receive the attached error message dialog box.

Any ideas?
![Screenshot from 2021-02-18 14-51-18](https://user-images.githubusercontent.com/75340371/108414072-c91f5000-71f9-11eb-94ad-4383a94dc051.png)

**Comment by AirVPN** [comment]
Confirmed, will be fixed in the next release.

**Comment by AirVPN** [comment]
This issue is fixed in the latest release 2.20.0.
