### ISSUE TITLE
set WM_CLASS for better Linux compatibility

### ISSUE THREAD

**Issue by sheivoko** [AirVPN/Eddie#26]
By default, Mono application windows do not have a WM_CLASS property.
This causes problems with Linux/X11 window managers, such as not being able to add the application's icon to docks: https://airvpn.org/topic/14911-add-eddie-icon-to-gnome-dock/

Please add support for the WM_CLASS property.
I have found some sample C# code that looks useful:
https://bitbucket.org/hindlemail/settingwmclass/

**Comment by AirVPN** [comment]
Done a lots of version ago.
