### ISSUE TITLE
Running GUI with `sudo` on linux prohibits ip6tables

### ISSUE THREAD

**Issue by smacz42** [AirVPN/Eddie#28]
So, I downloaded and installed the GUI client. When I went to run it, it asked for my Admin password. Since I only have my `root` account as a placeholder and haven't set it up, there _is_ no such password. So, from a terminal I ran `$ sudo airvpn` which took me right to the login screen. Everything started up, connected and looked to be working fine.

Then I navigated to airvpn, and noticed that an IPv6 leak was happening. I checked the output and found the line:

> Unable to understand if IPV6 is active

After scratching my head and googling around for a couple minutes, I ran

```
$ which ip6tables
[no output]

$ sudo which ip6tables
/sbin/ip6tables
```

Now I think I know what happened. Since I only ran the `airvpn` command with sudo, it wasn't running in a root shell with root privleges, just the regular user privleges. AKA it was unable to access ip6tables.

What worried me was that there was no indication of the possibility of a leak in the GUI, or that nothing further was done to determine if IPv6 was being used. Since I was focused on dealing with that exact problem at the time, I was able to notice it - but only after parsing through the output on the terminal. I felt the need to point out the lack of notification in the GUI and the bug that lead to this issue (`sudo` vs `su`, `gksudo` or `kdesudo`). It is not an issue in my case, but if apropriate, I would like to open a bug report for this behavior if it is not already known behavior.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
