### ISSUE TITLE
Windows Client does not set DNS Server back to previous settings,

### ISSUE THREAD

**Issue by liftir** [AirVPN/Eddie#29]
When exiting the client in windows, the client does not return the network adapters to their previous settings.  They still have the airvpn dns ip address in TCP IP v4 settings for the network adapters in use.

**Comment by geobeo** [comment]
I have this same issue still in the current AirVPN release version. 

Have to reset the DNS server manually to be able to continue using the connection after AirVPN closes... Annoying and it completely breaks internet for users who are not tech-savy...

**Comment by liftir** [comment]
I made a bat file and a shortcut with run as admin enabled to work around this bug.  Will post the bat later when I'm at my computer.

**Comment by geobeo** [comment]
Would love that bat file!

**Comment by liftir** [comment]
sorry for late response.  here's the bat file:
--
@echo off
netsh interface ipv4 set dnsservers "NIC_NAME_HERE" dhcp
--
Where NIC_NAME_HERE is, replace it with the name of your network card as shown in Network Connections.   If it doesn't work it may be because you need admin rights to make this change,, so like I said previously, create a shortcut that executes the bat file as admin.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
