### ISSUE TITLE
Unnecessary delays 

### ISSUE THREAD

**Issue by geobeo** [AirVPN/Eddie#41]
Disclaimer: I haven't looked at the code yet. 

From the user perspective it seems like there are a whole lot of delays happening when connecting/disconnecting to VPN servers. It seems to me this is the main reason AirVPN is (IMO) very slow when connecting/disconnecting, even on very fast connections. 

It would be very nice if some delays could be removed or at least made configurable in the GUI (under advanced settings for example). 

An example of a delay that seems totally unnecessary: when connected to a VPN server and reconnecting to a new one by doubleclicking a new server a disconnect routine is started. After the disconnect there's a 3 second countdown (for no reason?) until AirVPN tries to connect to the newly selected server. 

Another example is when a user cancels the connection routine: this should happen within an instance (a few ms at most?). However this takes ages (tens of seconds) where the connection routine is first allowed to finish connecting (takes ages) and then a disconnect routine is started with tons of delays etc (takes even "more ages"). Why? Just close/drop the socket and let the connection time out on the server side instead? 

I'm guessing there are also delays in the connection/deconnection threads. It would be super nice if these where configurable. It seems some of the delay's are multiple seconds where I would prefer something like 50ms at most (my ping to VPN servers is at most 10ms at all times). 

Another unrelated personal annoyance with the VPN client: the "are you sure you want to exit?" pop-up when closing the AirVPN client. This is especially frustrating since it cancels/blocks a shutdown request in Windows: the user needs to press "yes" for the shutdown to continue.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
