### ISSUE TITLE
[Feature Request] user-defined scripts or ovpn.AppendFile() equivalent

### ISSUE THREAD

**Issue by rprimus** [AirVPN/Eddie#58]
Sat 15 Apr 2017 19:41:33 BST

As a **VERY** advanced feature,  can a user defined script be run just
before the VPN is established?

The script could allow settings to be appended to the generated .ovpn file -
similar functionality to the function ```ovpn.AppendDirective()``` that Eddie
uses.

If this is considered to be too **dangerous**,  an alternative would be to append
the contents of a pre-determined file (if the file exists).

At the moment,  I'm only considering routes to be added.  This would be much easier than
using the GUI to manage routes individually.

Thoughts?

**Comment by Clodo76** [comment]
Hi, undecided about the right approach. You typically need to add directives based on server/country/protocols etc? Must be parameters of the user-defined script shell, and the output of the shell used for ovpn.AppendDirective()? 
For the moment, i will add a generic option "openvpn.directives.path" option in the next release.
If path found, it's read as text file and each line are passed to ovpn.AppendDirective().

**Comment by rprimus** [comment]
On Wed, May 17, 2017 at 04:08:48AM -0700, Clodo76 wrote:
> Hi, undecided about the right approach. You typically need to add directives based on server/country/protocols etc? Must be parameters of the user-defined script shell, and the output of the shell used for ovpn.AppendDirective()? 
> For the moment, i will add a generic option "openvpn.directives.path" option in the next release.
> If path found, it's read as text file and each line are passed to ovpn.AppendDirective().

Wed 17 May 2017 14:12:24 BST

HI,

Your suggestion would be sufficient!  

Many thanks.
> 

-- 
-primus (Train yourself and be your own master.)
"First, solve the problem.  Then, write the code." - John Johnson
"Narrowness of experience leads to narrowness of imagination." - Rob Pike
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: 0x28E92848DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by rprimus** [comment]
Fri Jun  9 17:01:11 BST 2017

hanks for adding in ```2.13.1```.  Will test!

**Comment by rprimus** [comment]
Mon Mar 12 10:24:36 GMT 2018

Hi,

Just realised that I forgot to post my results.   This works flawlessly.

Many thanks!!
