### ISSUE TITLE
curl.exe problem with updating systems and servers

### ISSUE THREAD

**Issue by scrumkick** [AirVPN/Eddie#75]
ystems & servers data update completed
. 2018.01.15 03:00:43 - Updating systems & servers data ...
. 2018.01.15 03:00:45 - Systems & servers data update completed
. 2018.01.15 03:11:03 - Updating systems & servers data ...
. 2018.01.15 03:11:05 - Systems & servers data update completed
. 2018.01.15 03:21:48 - Updating systems & servers data ...
. 2018.01.15 03:23:51 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30014 milliseconds with 2241 out of 75712 bytes received)
. 2018.01.15 03:32:31 - Updating systems & servers data ...
. 2018.01.15 03:34:36 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30015 milliseconds with 6306 out of 75712 bytes received)
continous problem

something else
curl.exe is extremely slowing down network connectivity

 2018.01.15 13:36:36 - OpenVPN > Initialization Sequence Completed
. 2018.01.15 13:40:18 - Updating systems & servers data ...
. 2018.01.15 13:41:28 - Systems & servers data update completed
. 2018.01.15 13:50:39 - Updating systems & servers data ...
. 2018.01.15 13:50:42 - Systems & servers data update completed
. 2018.01.15 14:00:57 - Updating systems & servers data ...
. 2018.01.15 14:00:59 - Systems & servers data update completed
. 2018.01.15 14:11:17 - Updating systems & servers data ...
. 2018.01.15 14:11:19 - Systems & servers data update completed
. 2018.01.15 14:21:34 - Updating systems & servers data ...
. 2018.01.15 14:21:36 - Systems & servers data update completed
. 2018.01.15 14:32:37 - Updating systems & servers data ...
. 2018.01.15 14:34:38 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30014 milliseconds with 2235 out of 75744 bytes received)
. 2018.01.15 14:36:07 - OpenVPN > TLS: soft reset sec=0 bytes=2701121622/-1 pkts=4859602/0
. 2018.01.15 14:37:07 - OpenVPN > TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
. 2018.01.15 14:37:07 - OpenVPN > TLS Error: TLS handshake failed
. 2018.01.15 14:37:07 - OpenVPN > TLS: move_session: dest=TM_LAME_DUCK src=TM_ACTIVE reinit_src=1

again and again

2018.01.15 14:52:53 - Updating systems & servers data ...
. 2018.01.15 14:53:13 - Systems & servers data update completed
. 2018.01.15 15:03:23 - Updating systems & servers data ...
. 2018.01.15 15:03:25 - Systems & servers data update completed
. 2018.01.15 15:13:53 - Updating systems & servers data ...
. 2018.01.15 15:15:55 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30014 milliseconds with 3587 out of 75744 bytes received)
. 2018.01.15 15:23:58 - Updating systems & servers data ...
. 2018.01.15 15:26:02 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30014 milliseconds with 3587 out of 75744 bytes re

reset my firewalls to default and same old problem with curl.exe
. 2018.01.15 17:11:04 - OpenVPN > Initialization Sequence Completed
. 2018.01.15 17:20:33 - Updating systems & servers data ...
. 2018.01.15 17:22:35 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30015 milliseconds with 6291 out of 75712 bytes received)

 2018.01.15 17:47:15 - Systems & servers data update completed
. 2018.01.15 17:57:59 - Updating systems & servers data ...
. 2018.01.15 18:00:01 - Cannot retrieve systems & servers data. (curl: (28) Operation timed out after 30015 milliseconds with 11744 out of 75728 bytes received)

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
