### ISSUE TITLE
Network lock fails with iptables 1.6.2

### ISSUE THREAD

**Issue by warptozero** [AirVPN/Eddie#78]
After updating iptables (1.6.1 > 1.6.2) network lock fails with the following message: 
`/usr/bin/iptables-save: unrecognized option '--wait'`

**Comment by aa23** [comment]
I had the same issue.
For those running Eddie on Arch Linux, you can quickly downgrade with:
`sudo pacman -U https://archive.archlinux.org/packages/i/iptables/iptables-1.6.1-2-x86_64.pkg.tar.xz`

**Comment by eddiebugs** [comment]
I confirm this issue on Debian 8 and Kali Linux.
Please patch Eddie soon. Thanks
