### ISSUE TITLE
Network lock fails to activate, but Eddie still starts.

### ISSUE THREAD

**Issue by rahmnathan** [AirVPN/Eddie#90]
Using the cli in a Docker image I specified '-netlock', but because there was no available network lock strategy I got the following message "There is no available or enabled Network Lock mode, sorry.". This would've been fine if I had actually noticed it, but I didn't. Turns out, my image doesn't have iptables installed by default.

I think Eddie should fail to start here instead so that the user is forced to either remove '-netlock' or fix the netlock issue (install iptables in my case). This log statement went unnoticed until I detected a vpn leak, which is too late.

I found that the log statement is coming from line 121 of the NetworkLockManager.cs file.

**Comment by AirVPN** [comment]
Fixed in upcoming release 2.19.4 (if netlock fail to activate, warning and disable autoconnect). Thanks.
