### ISSUE TITLE
[Feature Request] Respect XDG Basedir specs

### ISSUE THREAD

**Issue by jfowl** [AirVPN/Eddie#96]
Hey, I've seen that eddie (at least when run under linux) stores configuration under $HOME/.airvpn.
It would be awesome, if you could adher to the de-facto standard of not creating your own .dotfiles/dotdirs in the home directory <3

See the spec for more info: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics

**Comment by lhanson** [comment]
Please implement, don't invade my `$HOME` with arbitrary directories.

**Comment by AirVPN** [comment]
From 2.18.9 and above, it follow $XDG_CONFIG_HOME or use $HOME/.config/eddie.
