### ISSUE TITLE
Connection fails with third party VPN profile

### ISSUE THREAD

**Issue by theincogtion** [AirVPN/Eddie#99]
I try to connect to a VPN running in my home network.

With OpenVPN GUI it works fine.
With Eddie it fails
It stops at

`OpenVPN > MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:3100`

It does not show any other message, it even does not cancel. It tries to connect to localhost 3100 and isn't successful until I cancel it after some minutes waiting.
Connecting to airvpn server is no problem it just affects my private VPN.

 The config file in question:

```
client
dev tun
proto udp
remote xxxx 54555
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
```

Eddie is on version 2.17.2
Windows 10 is the OS
Firewall is off and antivir is Windows Defender.

**Comment by AirVPN** [comment]
This issue was addressed after the old 2.17.2
Please reopen if you still encounter this issue with the latest stable version.

Thank you!
